### PR TITLE
Added ESM and UMD bundles to the package

### PR DESCRIPTION
**Pull request by bhovhannes**
This PR adds a ESM and UMD modules to the package.

That will allow to use `@pinnacleio/react-event` with Rollup without additional plugins like (rollup-plugin-node-resolve and rollup-plugin-commonjs).

Additionally, I've upgraded rollup and friends to the latest version, because the version in use was too old.

I've added UMD bundle, too, to allow using `@pinnacleio/react-event` in browser either via script tag or using RequireJS.

### CODE REVIEW

**Comment by bhovhannes** [comment]
@rpunkfu, thank you for the package!

Can you please process this PR?  
Absence of ESM build makes it hard to consume this package using rollup.

**Comment by rpunkfu** [comment]
Sorry, didn't have time to look at this.
Will review in 1-2 days and merge if looks good, thanks a lot for your contribution. :)

**Comment by rpunkfu** [comment]
Thanks for you contribution @bhovhannes :)

**Comment by bhovhannes** [comment]
@rpunkfu thank you for merging, can you release a new package version?

**Pull request merged**
